### ISSUE TITLE
Rename feature seems to do nothing

### ISSUE THREAD

**Issue by oerp-odoo** [sublimelsp/LSP-pyright#95] opened 2021-11-09 17:50 UTC
When I hover over variable, for example, I see `RENAME` option, when I click it I get pop up where it allows me to change name. Though after changing it and pressing ENTER, nothing happens.

What that RENAME option supposed to do?
![Selection_188](https://user-images.githubusercontent.com/7812986/140977504-ccaefeea-6abb-4a6e-9767-92f4e2609a78.png)

**Comment by jfcherng** [comment] 2021-11-09 19:33
hmmm... works for me, even if in a single file (non-project) case.

**Comment by rchl** [comment] 2021-11-09 19:34
Enabling `log_server` (https://lsp.sublimetext.io/troubleshooting/) might reveal something.

**Comment by predragnikolic** [comment] 2022-08-10 13:38
Cannot reproduce,
can we close this?

**Comment by jfcherng** [comment] 2022-08-10 13:47
Closed because can't reproduce and inactiveness.

**Closed by jfcherng** 2022-08-10 13:47 UTC
Labels: await response

**Comment by rchl** [comment] 2022-08-10 13:50
It was reproducible :)
But it was fixed in LSP and I've also added a small note to the readme: f36a6e3b6659398c392f83e2b6449b430a4be2c5
