### ISSUE TITLE
Pyright does not pick up new files.

### ISSUE THREAD

**Issue by Fingel** [sublimelsp/LSP-pyright#94] opened 2021-11-05 21:52 UTC
I'm not sure if this is an upstream bug or not, but when I create a new Python file and then try to import something from it in a a different python file, pyright will complain about undefined imports. I have to restart lsp-pyright for them to be picked up.

**Comment by jfcherng** [comment] 2021-11-06 03:20
Iirc it's a ST core issue that there is no callback when files are created/deleted/modified by an external program.

**Comment by rchl** [comment] 2021-11-06 07:30
What platform are you on @Fingel?

You could see if it reproduces with https://packagecontrol.io/packages/LSP-file-watcher-chokidar installed but the last time I checked, pyright had been running its own file watcher and whether LSP supported file watching didn't really matter.

If you can still reproduce with that package then fell free to create a small repro and state your node version and OS.

**Comment by jfcherng** [comment] 2021-11-06 09:33
Pyright doesn't seem to watch a newly created  file by an external process but after installing https://packagecontrol.io/packages/LSP-file-watcher-chokidar and config it for watching .py files, Pyright works on my side.

- Node: v16.13.0
- OS: Win10 x64 21H1 (19043.1320

https://user-images.githubusercontent.com/6594915/140605047-587935fb-2e32-436e-a7e8-d3f68227b392.mp4

**Comment by rwols** [comment] 2021-11-06 09:41
So I guess it would be nice to have that in the default config

**Comment by rchl** [comment] 2021-11-06 09:51
That raises some questions though:
 - why pyright doesn't handle it itself since it's already running a file watcher
 - why it doesn't use dynamic registration to register watchers and requires manual configuration like old server?

Those should probably be asked in the pyright repo.

**Comment by jfcherng** [comment] 2021-11-06 10:10
When I created `new_file.py`, I see the following payload in VSCode (Pylance)

```js
[Trace - 下午6:08:29] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "file:///c%3A/Users/Tester/Desktop/my_project/my_package/new_file.py",
            "type": 1
        },
        {
            "uri": "file:///c%3A/Users/Tester/Desktop/my_project/my_package",
            "type": 2
        }
    ]
}
```

So I think it's VSCode's responsibility to notify Pylance there is a new file to be watched?

**Comment by rchl** [comment] 2021-11-06 10:33
> So I think it's VSCode's responsibility (or something from the client side) to notify Pylance there is a new file to be watched?

The client notifies, yes, but the client is told what to notify about either through manual configuration or dynamic registration from the server.

**Comment by rchl** [comment] 2021-11-06 10:46
How do you enable trace logs for pylance? Those dons't seem to do it:

```
  "pylance.trace.server": "verbose",
  "python.analysis.logLevel": "Trace"
```

**Comment by jfcherng** [comment] 2021-11-06 10:51
> How do you enable trace logs for pylance?

I use 

```
"python.trace.server": "verbose",
```

**Comment by rchl** [comment] 2021-11-06 10:57
> How do you enable trace logs for pylance?

Thanks. Realized before deleting the question. :)

So in Pylance the registration is done dynamically:

```

[Trace - 11:46:56 AM] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "4a407254-aede-40aa-b2a6-1dbb7e387c8d",
            "method": "workspace/didChangeWatchedFiles",
            "registerOptions": {
                "watchers": [
                    {
                        "globPattern": "**/pyrightconfig.json",
                        "kind": 7
                    },
                    {
                        "globPattern": "**",
                        "kind": 7
                    }
                ]
            }
        }
    ]
}
```

It would make sense to ask on the pyright repo to change pyright to do that itself.

Though I always think that they will be hesitant to add stuff because it would take away the competitive advantage of pylance...

**Comment by rchl** [comment] 2021-11-06 11:12
Ops... pyright actually registers the capability dynamically. The issue was on our side. I've made a silly mistake and reported the capability in the wrong place. Fixing in https://github.com/sublimelsp/LSP/pull/1892

With the fix it will be enough to install https://packagecontrol.io/packages/LSP-file-watcher-chokidar to have things working,

**Comment by rwols** [comment] 2021-11-06 11:13
I’d argue this is part of LSP functionality, not part of the “AI” competitive advantage :)

**Comment by rchl** [comment] 2021-11-06 11:15
Fun fact, the `**` watch pattern makes VSCode report changes to all files, even inside `.git/*`. On our side we filter out those most obvious non-code directories at least. I wonder why the pattern has to be so wide though.

**Comment by rchl** [comment] 2021-11-06 11:18
> I’d argue this is part of LSP functionality, not part of the “AI” competitive advantage :)

I still have this feeling every time I think of reporting some enhancement suggestion...

**Comment by jfcherng** [comment] 2021-11-06 11:19
> With the fix it will be enough to install [packagecontrol.io/packages/LSP-file-watcher-chokidar](https://packagecontrol.io/packages/LSP-file-watcher-chokidar) to have things working.

Do you mean we don't have to add `{"file_watcher": {"patterns": ["**/*.{py,pyi}"]}}` to settings since then?

**Comment by rchl** [comment] 2021-11-06 11:34
Yes, with the fix in place we don't need to define the file_watcher configuration manually since the server registers the watcher through a dynamic capability.

**Comment by predragnikolic** [comment] 2022-08-10 13:43
We now have LSP-file-watcher-chokidar as a current workaround that will fix this issue.

Can we close this,
because we already have an open ticket for tracking file watcher support in Sublime Text at https://github.com/sublimelsp/LSP/issues/892

**Comment by rchl** [comment] 2022-08-10 14:48
I think this is addressed with chokidar package, yes. Also LSP-pyright readme was updated to mention it.

**Closed by rchl** 2022-08-10 14:48 UTC
Labels: bug, upstream
