### ISSUE TITLE
Failed to start LSP-pyright

### ISSUE THREAD

**Issue by bdjurkan** [sublimelsp/LSP-pyright#73] opened 2021-06-05 16:10 UTC
![Screenshot-20210605180703-630x875](https://user-images.githubusercontent.com/2017564/120897995-4cd63e80-c629-11eb-8496-161d4d37fd49.png)

**Comment by predragnikolic** [comment] 2021-06-05 19:29
Here is a quick fix to try out,
Can you reinstall LSP-pyright? (a Sublime Text restart  might be necessary)

**Comment by jfcherng** [comment] 2021-06-05 23:14
That usually means somehow pyright is not properly installed but LSP-pyright thought pyright has been installed... Could you manually delete the directory `~/.cache/sublime-text/Package Storage/LSP-pyright` and restart ST?

**Comment by bdjurkan** [comment] 2021-06-06 12:00
I reinstalled LSP-pyright more than once, I manually deleted the directory ~/.cache/sublime-text/Package Storage/LSP-pyright and restarted Sublime but the message remained the same.
Interesting, but the day before yesterday everything worked.

Here is console message:

Package Control: Skipping automatic upgrade, last run at 2021-06-06 13:33:37, next run at 2021-06-06 14:33:37 or after
[lsp_utils] START output of command: "/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/bin/node/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/bin/npm-cli.jsci--scripts-prepend-node-path=true--verbose--production"

[lsp_utils] Command output END
Unable to start subprocess for LSP-pyright
Traceback (most recent call last):
  File "/home/boris/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 88, in install_or_update
    self._node_runtime.npm_install(self._server_dest)
  File "/home/boris/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/node_runtime.py", line 130, in npm_install
    raise Exception('Failed to run npm command "{}":\n{}'.format(' '.join(args), error))
Exception: Failed to run npm command "/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/bin/node /home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/bin/npm-cli.js ci --scripts-prepend-node-path=true --verbose --production":
internal/modules/cjs/loader.js:303
      throw err;
      ^

Error: Cannot find module '/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/node_modules/npmlog/log.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/bin/npm-cli.js:155:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/node_modules/npmlog/package.json',
  requestPath: 'npmlog'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boris/.config/sublime-text/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 310, in start_async
    plugin_class.install_or_update()
  File "/home/boris/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 108, in install_or_update
    server.install_or_update()
  File "/home/boris/.config/sublime-text/Packages/lsp_utils/st3/lsp_utils/server_npm_resource.py", line 91, in install_or_update
    raise Exception(error)
Exception: Failed to run npm command "/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/bin/node /home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/bin/npm-cli.js ci --scripts-prepend-node-path=true --verbose --production":
internal/modules/cjs/loader.js:303
      throw err;
      ^

Error: Cannot find module '/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/node_modules/npmlog/log.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/bin/npm-cli.js:155:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime/12.20.2/node/lib/node_modules/npm/node_modules/npmlog/package.json',
  requestPath: 'npmlog'
}

**Comment by bdjurkan** [comment] 2021-06-06 12:10
LSP-pyright work if I start Sublime from command line, but it does not work when I start Sublime normally.
Does anyone know what the problem is because the day before yesterday everything was working normally

**Comment by jfcherng** [comment] 2021-06-06 12:32
I can't reproduce it in my fresh Ubuntu VM... If you don't mind a fresh re-download, you can

1. Close ST
2. Delete following directories

   - `~/.cache/sublime-text/Package Storage/lsp_utils`
   - `~/.cache/sublime-text/Package Storage/LSP-pyright`

3. Start ST. 
4. Open a python file. You should be asked to download Node.js. After that, pyright should be downloaded as well.
5. Restart ST. Everything should be fine?

**Comment by bdjurkan** [comment] 2021-06-06 14:03
Everything is fine now.  I did exactly as you said. Thanks!
If not a problem, I would ask you one question regarding LSP-html.
How in settings enable LSP-html for html django (scope "text.html.django")?

**Comment by jfcherng** [comment] 2021-06-06 23:08
```
	"languages": [
		{
			"languageId": "html",
			// ST3 configuration
			"scopes": ["text.html.basic", "text.html.django"],
			"syntaxes": ["Packages/HTML/HTML.sublime-syntax", "I DONT KNOW THE PATH"],
			// ST4 configuration
			"document_selector": "text.html.basic | text.html.django",
			"feature_selector": "text.html",
		},
	],
```

**Comment by jfcherng** [comment] 2021-06-07 04:29
Closed as the origin issue has been resolve.

**Closed by jfcherng** 2021-06-07 04:29 UTC
Labels: question

**Comment by rchl** [comment] 2021-06-07 10:03
It looks like node in `/home/boris/.cache/sublime-text/Package Storage/lsp_utils/node-runtime` was not fully installed. Maybe installation was interrupted accidentally.
